// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARbwXgNFUfff3TjSv1-vn7ehc4XT3pPWE',
    appId: '1:957589231832:web:cb40bff4064aa1bca6dfad',
    messagingSenderId: '957589231832',
    projectId: 'stock-saas-abb28',
    authDomain: 'stock-saas-abb28.firebaseapp.com',
    databaseURL: 'https://stock-saas-abb28-default-rtdb.firebaseio.com',
    storageBucket: 'stock-saas-abb28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs1m7Z9gT7T7GvPu-ahvPDG5B8ROMKz7o',
    appId: '1:957589231832:android:a1d7958c1d5832c3a6dfad',
    messagingSenderId: '957589231832',
    projectId: 'stock-saas-abb28',
    databaseURL: 'https://stock-saas-abb28-default-rtdb.firebaseio.com',
    storageBucket: 'stock-saas-abb28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbWr07PbWzlHyp7R7MZ-Z-UcE69GTt1r0',
    appId: '1:957589231832:ios:eba0f93508eb7bb3a6dfad',
    messagingSenderId: '957589231832',
    projectId: 'stock-saas-abb28',
    databaseURL: 'https://stock-saas-abb28-default-rtdb.firebaseio.com',
    storageBucket: 'stock-saas-abb28.firebasestorage.app',
    iosBundleId: 'com.omarmegzari.stockFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbWr07PbWzlHyp7R7MZ-Z-UcE69GTt1r0',
    appId: '1:957589231832:ios:eba0f93508eb7bb3a6dfad',
    messagingSenderId: '957589231832',
    projectId: 'stock-saas-abb28',
    databaseURL: 'https://stock-saas-abb28-default-rtdb.firebaseio.com',
    storageBucket: 'stock-saas-abb28.firebasestorage.app',
    iosBundleId: 'com.omarmegzari.stockFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARbwXgNFUfff3TjSv1-vn7ehc4XT3pPWE',
    appId: '1:957589231832:web:6e71132ae75932b3a6dfad',
    messagingSenderId: '957589231832',
    projectId: 'stock-saas-abb28',
    authDomain: 'stock-saas-abb28.firebaseapp.com',
    databaseURL: 'https://stock-saas-abb28-default-rtdb.firebaseio.com',
    storageBucket: 'stock-saas-abb28.firebasestorage.app',
  );
}
